# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk
PackageVersion: 9.0.2
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ReleaseDate: 2025-01-16
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://download.anydesk.com/AnyDesk.exe
  InstallerSha256: 0DCEE93CBBF39F2E1D37024C279B0CD16409F08CC94FAA4FCCD285021022BFDA
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Upgrade: --remove-first
    Custom: --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
  UpgradeBehavior: install
  ElevationRequirement: elevationRequired
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
 InstallerSha256: 3ADEC63D12273021DFB5B8998B934E659B12CA1C2F799C7899DC7FEFF9EC7A0C
  UpgradeBehavior: uninstallPrevious
  ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
    ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
    UpgradeCode: '{ED0600A3-9843-4B5B-B47F-586E1C3FC53A}'
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.9.0
