# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: PDFsam.PDFsam
PackageVersion: 5.2.4
PackageLocale: en-US
Publisher: Sober Lemur S.a.s. di Vacondio Andrea
PublisherUrl: https://github.com/torakiki/pdfsam
PublisherSupportUrl: https://github.com/torakiki/pdfsam/issues
Author: Sober Lemur S.a.s. di Vacondio Andrea
PackageName: PDFsam Basic
PackageUrl: http://www.pdfsam.org/
License: AGPL-3.0
LicenseUrl: https://github.com/torakiki/pdfsam/blob/HEAD/LICENSE
CopyrightUrl: https://raw.githubusercontent.com/torakiki/pdfsam/master/LICENSE
ShortDescription: PDFsam Basic or PDF Split and Merge is a free and open-source cross-platform desktop application to split, merge, extract pages, rotate and mix PDF documents.
Tags:
- pdf
ManifestType: defaultLocale
ManifestVersion: 1.6.0
